### PR TITLE
Implements SQS as resource module

### PR DESCRIPTION
**Pull request by williamayerst**
#### 📲 What

AB#4212 - Implements SQS as resource module for CQRS+Messaging Dotnet Package

#### 🤔 Why

Needed for CQRS+Messaging Dotnet Package

#### 🛠 How

Standard TF

#### 👀 Evidence

n/a

#### 🕵️ How to test

Notes on how a reviewer can test the changes, e.g. how to run the tests.

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

### CODE REVIEW

**Comment by ElvenSpellmaker** [comment]
Hey Will, did you know there's already an SQS module? https://registry.terraform.io/modules/terraform-aws-modules/sqs/aws/latest

**Comment by williamayerst** [comment]
> Hey Will, did you know there's already an SQS module? https://registry.terraform.io/modules/terraform-aws-modules/sqs/aws/latest

I did @ElvenSpellmaker - I cribbed the resources from it, but it is maintained by a single individual so I feel metaphorically forking it is a better idea for stacks. Thoughts?

**Comment by ElvenSpellmaker** [comment]
> > Hey Will, did you know there's already an SQS module? [registry.terraform.io/modules/terraform-aws-modules/sqs/aws/latest](https://registry.terraform.io/modules/terraform-aws-modules/sqs/aws/latest)
> 
> I did @ElvenSpellmaker - I cribbed the resources from it, but it is maintained by a single individual so I feel metaphorically forking it is a better idea for stacks. Thoughts?

As far as I know they have to list a maintainer for the code, but they're maintained by AWS? We use those AWS modules heavily (although not this one) on my current project.

**Comment by williamayerst** [comment]
Fair play @ElvenSpellmaker - closing this PR.

**Pull request closed without merging**
